#!/usr/bin/env python2.7

import RPi.GPIO as GPIO
import time as t

GPIO.setmode(GPIO.BCM)

GPIO.setup(22, GPIO.OUT)

while True:
    GPIO.output(22, GPIO.HIGH)
    t.sleep(0.5)
    GPIO.output(22, GPIO.LOW)
    t.sleep(0.5)
