#!/usr/bin/env python3

import RPi.GPIO as GPIO
import time as t
import random as r

GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False)

pins = [4, 17, 22, 10]
for pin in pins:
    GPIO.setup(pin, GPIO.OUT)

def l_on(pin):
    GPIO.output(pin, GPIO.HIGH)

def l_off(pin):
    GPIO.output(pin, GPIO.LOW)

colors = ["r", "y", "g", "b"]

for round in range(1, 1000, 1):
    light_num = round + 1
    print("Round: {}".format(round))
    t.sleep(1)
    for countdown in range(3,0,-1):
        print("Starting in: {}".format(countdown))
        t.sleep(1)
    lights = []
    for light in range(1, light_num, 1):
        lights_add = r.choice(colors)
        lights.append(lights_add)
        if lights_add == "r":
            l_on(4)
            t.sleep(0.75)
            l_off(4)
            t.sleep(0.25)
        elif lights_add == "y":
            l_on(17)
            t.sleep(0.75)
            l_off(17)
            t.sleep(0.25)
        elif lights_add == "g":
            l_on(22)
            t.sleep(0.75)
            l_off(22)
            t.sleep(0.25)
        elif lights_add == "b":
            l_on(10)
            t.sleep(0.75)
            l_off(10)
            t.sleep(0.25)
        else:
            print("ERROR\nEXITING PROGRAM")
            t.sleep(0.3)
            exit()
    print("Please enter the letters: (R)ed,(Y)ellow,(G)reen and (B)lue\nIn the same order they flashed. (Do NOT use spaces. If you do it counts you wrong.)")
    user_answer = input(">>> ")
    user_answer = user_answer.strip().lower()
    if list(user_answer) == lights:
        print("Good job you passed this round.")
        t.sleep(0.5)
        print("Continuing on to nextround...")
        t.sleep(0.75)
    elif list(user_answer) != lights:
        print("You missed or got one or more letters incorrect.")
        t.sleep(0.5)
        print("Please restart the program to try again.")
        exit()
        
